version: '3.3'

services:
    db:
        image: postgres:12.0-alpine
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: always
        env_file:
            - ./.env
        networks:
            - djangonetwork
    
    frontend:
        image: chameleon812/infra_frontend_1:latest
        volumes:
            - ./frontend/:/app/result_build/
        depends_on:
            - db

    backend:
        image: chameleon812/infra_backend_1:latest
        restart: always
        volumes:
            - static_value:/app/static/
            - media_value:/app/media/
        depends_on:
            - db
        env_file:
            - ./.env
        networks:
            - djangonetwork


    nginx:
        image: nginx:1.19.3
        ports:
            - 80:80
        volumes:
            - static_value:/usr/share/nginx/html/
            - media_value:/usr/share/nginx/html/
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./frontend/build:/usr/share/nginx/html/
            - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
            - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
            - ./docs/:/usr/share/nginx/html/api/docs/
        volumes_from:
            - backend
        restart: always
        depends_on:
            - backend
            - frontend
        networks:
            - djangonetwork
networks:
      djangonetwork:
          driver: bridge
volumes :
    postgres_data:
    static_value:
    media_value: