version: '3.3'

services:
    db:
        image: postgres:12.0-alpine
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: always
        env_file:
            - ./.env
        networks:
            - djangonetwork

    backend:
        image: chameleon812/infra_backend_1:latest
        restart: always
        volumes:
            - media_value:/var/www/be/media_n/
            - backend:/app/static
        depends_on:
            - db
        env_file:
            - ./.env
        networks:
            - djangonetwork

    frontend:
        image: chameleon812/infra_frontend_1:latest
        volumes:
            - frontend/:/app/build
        depends_on:
            - db
            - backend

    nginx:
        image: nginx:1.19.3
        ports:
            - 80:80
        volumes:
            - media_value:/var/www/be/media_n/
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - frontend:/var/www/fe
            - backend:/var/www/be/static
        volumes_from:
            - backend
        restart: always
        depends_on:
            - backend
            - frontend
        networks:
            - djangonetwork
networks:
      djangonetwork:
          driver: bridge
volumes :
    postgres_data:
    media_value:
    frontend:
    backend:
