# Generated by Django 4.2 on 2023-05-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в избранное')),
            ],
            options={
                'verbose_name': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в список покупок')),
            ],
            options={
                'verbose_name': 'Покупки',
            },
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipe_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipe_text_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipe_pub_date_idx',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='shopping_carts',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='recipes.recipe', verbose_name='Покупка'),
        ),
    ]
