# Generated by Django 4.2 on 2023-09-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_favorite_options_remove_favorite_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Sopping list'},
        ),
    ]
