# Generated by Django 4.2 on 2023-09-22 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0009_shoppingcart_delete_shoppinglist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Shopping cart', 'verbose_name_plural': 'Shopping carts'},
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_recipe_cart',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='added',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='recipe',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='recipes',
            field=models.ManyToManyField(related_name='in_shopping_cart', to='recipes.recipe', verbose_name='Recipes'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
