# Generated by Django 4.2 on 2023-09-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_follow_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id'], 'verbose_name': 'User'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Subscription'},
        ),
    ]
